### ISSUE TITLE
Runtime Error during fetching

### ISSUE THREAD

**Issue by mzurs** [dappblock/nextjs-ic-starter#12]
Unhandled Runtime Error
TypeError: Failed to fetch

Source
ui/components/GreetingSection.js (21:21) @ async sayGreeting

  19 | 
  20 | const helloActor = makeHelloActor()
> 21 | const greeting = await helloActor.greet(name)
     |                 ^
  22 | 
  23 | setLoading("")
  24 | setGreetingMessage(greeting)

**Comment by samyabrata-maji** [comment]
add the NEXT_PUBLIC_IC_HOST in your `.env` file

**Comment by kinwo** [comment]
NEXT_PUBLIC_IC_HOST is in .env.development and .env.production. They are used by NextJS during build time.
