### ISSUE TITLE
Query for SSR

### ISSUE THREAD

**Issue by mzurs** [dappblock/nextjs-ic-starter#13]
From this note ```One thing to note is we use Next.js static code export here for hosting in Internet Computer so we can't use any features of Next.js that require server-side NodeJS. Potentially, there might be ways to use Internet Computer canister as a backend while deploying Next.js dapp to a hosting like Vercel that supports NodeJS servers in the future. Further research is needed on that aspect. However, if you do want to run everything decentralized on blockchain including the frontend, you would want to deploy the exported static code to Internet Computer as well.````

means that we are unable to use getServerSideProps and unable to use API/ route for serverside APIs. If yes, is there any alternative way to call API routes while hosting from frontend canister? Thanks!

**Comment by kinwo** [comment]
Hi @keccak-256 thanks for the question. There is a similar question about getServerSideProps in Dfinity forum. https://forum.dfinity.org/t/nextjs-ic-starter-simple-ic-starter-dapp-with-next-js-frontend-and-motoko/5560/7
In short, you can try:

```
useEffect(() => {
    async function loadPost() {

      if (router.query.id != null) {
          // Load post content from IC Canister actor or fetch from external serverside API hosted in Vercel or cloud
      }
    }


    loadPost()

  }, [router.query.id])
```

Another way is to SWR React Hook from Vercel. https://swr.vercel.app. I have an example in Beam app..
https://github.com/BeamFi/beamapp/blob/03436e33f334d348aff490b931d9361cb3b9ec49/ui/components/beam/useEscrow.tsx#L4

It calls Canister to load data but you can simply switch it to fetch from other serverside API.

Hope that helps!

**Comment by kinwo** [comment]
Ideally, your server side logic should be in IC smart contract. If you mean the new NextJS / React Server Component, I think only the static rendering will during build time in Static Export. Try to look into the beta NextJS docs https://beta.nextjs.org/docs/rendering/fundamentals. You may find some clues there. Cheers.
