### ISSUE TITLE
Issues in adding tailwindcss

### ISSUE THREAD

**Issue by SandeepKumarYaramchitti** [dappblock/nextjs-ic-starter#9]
Do you have any example with tailwindcss integrated in this ? Somehow, it is not picking tailwindcss classes ?

**Comment by kinwo** [comment]
Hi, since this project is based on NextJS, did you try the NextJS + Tailwind CSS integration guide?
https://tailwindcss.com/docs/guides/nextjs

It might be an issue with missing global.css.
./styles/globals.css
